service: pipeline-bovespa-fiap
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  memorySize: 128
  timeout: 30

  environment:
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID} 

  iam:
    role: arn:aws:iam::${self:provider.environment.AWS_ACCOUNT_ID}:role/LabRole

functions:
  scrapB3:
    handler: scripts/scrap_b3.scrap_b3
    events:
      - schedule: cron(0 22 * * ? *) # Executa diariamente às 22h
  triggerGlue:
    handler: scripts/lambda_trigger.lambda_handler
    memorySize: 256  # Aumente para evitar problemas durante o teste
    timeout: 30
    events:
      - s3:
          bucket: bucketfiapgrupo129-tech2
          event: s3:ObjectCreated:*
          rules:
            - prefix: raw/

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true  # Remove arquivos desnecessários (ex.: testes, docs)
    layer: true # Usa uma Lambda Layer para dependências grandes
    dockerizePip: true  # Usa contêiner compatível com o ambiente do Lambda
    useStaticCache: false
    useDownloadCache: false

package:
  patterns:
    - "!node_modules/**"
    - "!__pycache__/**"

resources:
  Resources:
    GlueJob:
      Type: AWS::Glue::Job
      Properties:
        Name: Job-Glue-Bovespa
        Role: arn:aws:iam::${self:provider.environment.AWS_ACCOUNT_ID}:role/LabRole
        Command:
          Name: glueetl
          ScriptLocation: s3://bucketfiapgrupo129-tech2/scripts/glue_script.py
          PythonVersion: 3
